# Задания практической работы #

## 1. Создание и изменение массивов ##

Создайте массив NumPy размером 3х3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [1]:
import numpy as np

# Создаем массив 3x3 с числами от 1 до 9
arr = np.arange(1, 10).reshape(3, 3)
print("Исходный массив:")
print(arr)

# Умножаем все элементы на 2
arr = arr * 2
print("\nМассив после умножения на 2:")
print(arr)

# Заменяем элементы > 10 на 0
arr[arr > 10] = 0
print("\nИтоговый массив:")
print(arr)

Исходный массив:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Массив после умножения на 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Итоговый массив:
[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


## 2. Работа с булевыми масками ##
Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.


In [2]:
arr = np.random.randint(1, 101, 20)
print("Исходный массив:")
print(arr)

# Находим элементы, кратные 5
mask = arr % 5 == 0
multiples_of_5 = arr[mask]
print("\nЭлементы, кратные 5:")
print(multiples_of_5)

# Заменяем их на -1
arr[mask] = -1
print("\nОбновленный массив:")
print(arr)

Исходный массив:
[30 45 15 70  2 96 77 14 94 79 15 77 33 50 76 34 58 76 73 56]

Элементы, кратные 5:
[30 45 15 70 15 50]

Обновленный массив:
[-1 -1 -1 -1  2 96 77 14 94 79 -1 77 33 -1 76 34 58 76 73 56]


## 3. Объединение и разбиение массивов ##
Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50.

- Объедините эти массивы в один двумерный массив (по строкам).
- Разделите полученный массив на два массива, каждый из которых содержит 5 элементов.

Выведите все промежуточные и итоговые результаты.

In [3]:
arr1 = np.random.randint(0, 51, 5).reshape(1, 5)
arr2 = np.random.randint(0, 51, 5).reshape(1, 5)

print("Первый массив:")
print(arr1)
print("\nВторой массив:")
print(arr2)

# Объединяем массивы по строкам
combined = np.vstack((arr1, arr2))
print("\nОбъединенный массив:")
print(combined)

# Разделяем массив на два массива по 5 элементов
split_arr = np.split(combined, 2)
print("\nПервый разделенный массив:")
print(split_arr[0].flatten())
print("\nВторой разделенный массив:")
print(split_arr[1].flatten())

Первый массив:
[[ 3 18 40 18 11]]

Второй массив:
[[ 8 46 15 38 33]]

Объединенный массив:
[[ 3 18 40 18 11]
 [ 8 46 15 38 33]]

Первый разделенный массив:
[ 3 18 40 18 11]

Второй разделенный массив:
[ 8 46 15 38 33]


## 4. Генерация и работа с линейными последовательностями ##
Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму
отрицательных элементов. Выведите результаты.

In [2]:
import numpy as np

# Создаем массив из 50 чисел от -10 до 10
arr = np.linspace(-10, 10, 50)
print("Сгенерированный массив:")
print(arr)

# Вычисляем суммы
total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print("\nРезультаты:")
print(f"Сумма всех элементов: {total_sum:.2f}")
print(f"Сумма положительных элементов: {positive_sum:.2f}")
print(f"Сумма отрицательных элементов: {negative_sum:.2f}")

Сгенерированный массив:
[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Результаты:
Сумма всех элементов: 0.00
Сумма положительных элементов: 127.55
Сумма отрицательных элементов: -127.55


## 5. Работа с диагональными и единичными матрицами ##
Создайте:

- Единичную матрицу размером 4х4.
- Диагональную матрицу размером 4х4 с диагональными элементами[5,10,15,20](не использовать циклы).

Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [5]:
# Создаем единичную матрицу 4×4
identity_matrix = np.eye(4)
print("Единичная матрица:")
print(identity_matrix)

# Создаем диагональную матрицу с заданными элементами
diagonal_elements = [5, 10, 15, 20]
diagonal_matrix = np.diag(diagonal_elements)
print("\nДиагональная матрица:")
print(diagonal_matrix)

# Вычисляем суммы элементов
sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print("\nСравнение сумм:")
print(f"Сумма элементов единичной матрицы: {sum_identity}")
print(f"Сумма элементов диагональной матрицы: {sum_diagonal}")

if sum_identity > sum_diagonal:
    print("Единичная матрица имеет большую сумму элементов")
elif sum_identity < sum_diagonal:
    print("Диагональная матрица имеет большую сумму элементов")
else:
    print("Матрицы имеют одинаковую сумму элементов")

Единичная матрица:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Диагональная матрица:
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]

Сравнение сумм:
Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Диагональная матрица имеет большую сумму элементов


## 6. Создание и базовые операции с матрицами ##
Создайте две квадратные матрицы NumPy размером 3х3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите:

- Их сумму
- Их разность
- Их поэлементное произведение


In [6]:
matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

print("Первая матрица:")
print(matrix1)
print("\nВторая матрица:")
print(matrix2)

# Вычисляем операции
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_elementwise = matrix1 * matrix2

print("\nРезультаты операций:")
print("\nСумма матриц:")
print(matrix_sum)
print("\nРазность матриц:")
print(matrix_diff)
print("\nПоэлементное произведение:")
print(matrix_elementwise)

Первая матрица:
[[16  6 10]
 [ 1  7  3]
 [15  6 10]]

Вторая матрица:
[[16  5  5]
 [17  8 11]
 [14 14 12]]

Результаты операций:

Сумма матриц:
[[32 11 15]
 [18 15 14]
 [29 20 22]]

Разность матриц:
[[  0   1   5]
 [-16  -1  -8]
 [  1  -8  -2]]

Поэлементное произведение:
[[256  30  50]
 [ 17  56  33]
 [210  84 120]]


## 7. Умножение матриц ##
Создайте два матрицы NumPy:

- Первую размером 2х3, заполненную случайными числами от 1 до 10.
- Вторую размером 3х2, заполненую случайными числами от 1 до 10.

Выполните матричное умножение и выведите результат.

In [9]:
matrix_a = np.random.randint(1, 11, size=(2, 3))
print("Матрица A (2x3):")
print(matrix_a)

# Создаем матрицу 3x2
matrix_b = np.random.randint(1, 11, size=(3, 2))
print("\nМатрица B (3x2):")
print(matrix_b)

# Выполняем матричное умножение
result = np.dot(matrix_a, matrix_b)  # или np.dot(matrix_a, matrix_b)
print("\nРезультат матричного умножения:")
print(result)

Матрица A (2x3):
[[5 9 7]
 [8 1 8]]

Матрица B (3x2):
[[2 6]
 [9 8]
 [9 5]]

Результат матричного умножения:
[[154 137]
 [ 97  96]]


## 8. Определитель и обратная матрица ##
Создайте случайную квадратную матрицу 3х3. Найдите и выведите:

- Определитель этой матрицы
- Обратную матрицу(если существует, иначе выведите сообщению, что матрица вырождена)

Используйте функции np.linalg.det и np.linalg.inv.

In [11]:
matrix = np.random.randint(1, 10, size=(3, 3))
print("Исходная матрица:")
print(matrix)

# Вычисляем определитель
det = np.linalg.det(matrix)
print(f"\nОпределитель матрицы: {det:.2f}")

# Проверяем обратимость матрицы и вычисляем обратную
if not np.isclose(det, 0):
    inv_matrix = np.linalg.inv(matrix)
    print("\nОбратная матрица:")
    print(inv_matrix)
else:
    print("\nМатрица вырождена (определитель равен 0), обратной матрицы не существует")

Исходная матрица:
[[8 7 7]
 [8 8 4]
 [5 3 2]]

Определитель матрицы: -52.00

Обратная матрица:
[[-0.07692308 -0.13461538  0.53846154]
 [-0.07692308  0.36538462 -0.46153846]
 [ 0.30769231 -0.21153846 -0.15384615]]


## 9. Транспонирование и след матрицы ##
Создайте матрицу NumPy размером 4х4, содержащую случайные целые числа от 1 до 50. Выведите:

- Исходную матрицу
- Траспонированную матрицу
- След матрицы(сумму всех элементов на главной диагонали)

Используйте np.trace для нахождение следа.

In [12]:
matrix = np.random.randint(1, 51, size=(4, 4))
print("Исходная матрица:")
print(matrix)

# Транспонируем матрицу
transposed = matrix.T
print("\nТранспонированная матрица:")
print(transposed)

# Вычисляем след матрицы
trace = np.trace(matrix)
print(f"\nСлед матрицы (сумма диагональных элементов): {trace}")

Исходная матрица:
[[11 19 37 49]
 [27 37 14  6]
 [17  3 35 49]
 [32 11 31 33]]

Транспонированная матрица:
[[11 27 17 32]
 [19 37  3 11]
 [37 14 35 31]
 [49  6 49 33]]

След матрицы (сумма диагональных элементов): 116


## 10. Системы линейных уравнений ##
Решите систему линейных уравнений вида:
$$\begin{cases} 
2x + 3y - z = 5 \\ 
4x - y + 2z = 6 \\ 
-3x + 5y + 4z = -2 
\end{cases}$$

Используйте матричное представление Ax = B, где А - это матрица коэффициентов, x - вектор неизвестных, B - вектор правой части. Решите систему с помощью np.linalg.solve и выведите результат.

In [3]:
# Матрица коэффициентов
A = np.array([
    [2, 3, -1],
    [4, -1, 2],
    [-3, 5, 4]
])

# Вектор правой части
B = np.array([5, 6, -2])

# Решение системы
try:
    solution = np.linalg.solve(A, B)
    print("Решение системы:")
    print(f"x = {solution[0]:.2f}")
    print(f"y = {solution[1]:.2f}")
    print(f"z = {solution[2]:.2f}")
except np.linalg.LinAlgError:
    print("Система не имеет единственного решения (матрица вырождена)")

Решение системы:
x = 1.64
y = 0.58
z = 0.01


## 11. Индивидуальное задание ##
Решите индивидуальное задание согласно варианта. Каждое задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

*12. Продажа билетов.* На концерт продано 500 билетов трех категорий: стандартные, премиум и VIP. Билеты премиум стоят в 1.5 раза дороже стандартных, а VIP — в 2 раза дороже премиум. Общий доход от продажи составил 600 000 рублей. Сколько билетов каждого типа было продано, если известно, что стандартных билетов было на 100 больше, чем премиум?

In [1]:
import numpy as np

# Дано:
total_tickets = 500
total_income = 600000
premium_to_standard_ratio = 1.5
vip_to_premium_ratio = 2
standard_more_than_premium = 100

# Система уравнений:
# 1) x + y + z = 500
# 2) x + 1.5y + 3z = 600 (предполагаем p=1000)
# 3) x = y + 100

# Матрица коэффициентов и вектор свободных членов
A = np.array([
    [1, 1, 1],
    [1, 1.5, 3],
    [1, -1, 0]
])
B = np.array([500, 600, 100])

# Решение с помощью np.linalg.solve
solution_linalg = np.linalg.solve(A, B)
x_linalg, y_linalg, z_linalg = solution_linalg

# Метод Крамера
def cramer_solve(A, B):
    det_A = np.linalg.det(A)
    solutions = []
    for i in range(len(B)):
        Ai = A.copy()
        Ai[:, i] = B
        det_Ai = np.linalg.det(Ai)
        solutions.append(det_Ai / det_A)
    return solutions

solution_cramer = cramer_solve(A, B)
x_cramer, y_cramer, z_cramer = solution_cramer

# Матричный метод
A_inv = np.linalg.inv(A)
solution_matrix = A_inv.dot(B)
x_matrix, y_matrix, z_matrix = solution_matrix

# Проверка доходов
p_standard = 1000  # предположение
p_premium = p_standard * premium_to_standard_ratio
p_vip = p_premium * vip_to_premium_ratio

income_linalg = (x_linalg * p_standard + y_linalg * p_premium + z_linalg * p_vip)
income_cramer = (x_cramer * p_standard + y_cramer * p_premium + z_cramer * p_vip)
income_matrix = (x_matrix * p_standard + y_matrix * p_premium + z_matrix * p_vip)

# Вывод результатов
print("Решение системы линейных уравнений:")
print(f"Метод np.linalg.solve: x = {x_linalg:.0f}, y = {y_linalg:.0f}, z = {z_linalg:.0f}")
print(f"Метод Крамера:         x = {x_cramer:.0f}, y = {y_cramer:.0f}, z = {z_cramer:.0f}")
print(f"Матричный метод:       x = {x_matrix:.0f}, y = {y_matrix:.0f}, z = {z_matrix:.0f}")

print("\nПроверка дохода:")
print(f"np.linalg.solve: {income_linalg:.0f} руб.")
print(f"Метод Крамера:    {income_cramer:.0f} руб.")
print(f"Матричный метод:  {income_matrix:.0f} руб.")

print("\nИтоговый ответ:")
print(f"Стандартных билетов: {int(round(x_linalg))}")
print(f"Премиум билетов:     {int(round(y_linalg))}")
print(f"VIP билетов:        {int(round(z_linalg))}")

Решение системы линейных уравнений:
Метод np.linalg.solve: x = 300, y = 200, z = 0
Метод Крамера:         x = 300, y = 200, z = 0
Матричный метод:       x = 300, y = 200, z = 0

Проверка дохода:
np.linalg.solve: 600000 руб.
Метод Крамера:    600000 руб.
Матричный метод:  600000 руб.

Итоговый ответ:
Стандартных билетов: 300
Премиум билетов:     200
VIP билетов:        0
